[package]
name = "depyler-verify"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
depyler-core = { path = "../depyler-core" }
depyler-annotations = { path = "../depyler-annotations" }
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
quickcheck.workspace = true
proptest.workspace = true
smallvec = { version = "1.0", features = ["serde"] }

[dev-dependencies]
insta.workspace = true
quickcheck_macros = "1.0"