# PMAT Configuration for Depyler Playground
# Following Toyota Production System principles

[targets]
# Time to First Meaningful Paint target (P50) in milliseconds
ttfmp_p50_ms = 800.0

# Time to Interactive target (P90) in milliseconds  
tti_p90_ms = 2000.0

# WASM size budget in KB (gzipped)
wasm_size_budget_kb = 1500.0

[targets.transpile_targets]
# Simple functions (<10 lines) - P95 latency target
simple_p95_ms = 50.0

# Medium complexity (10-50 lines) - P95 latency target
medium_p95_ms = 200.0

# Complex functions (>50 lines) - P95 latency target
complex_p95_ms = 1000.0

[scoring]
# Sigmoid function steepness for smooth score transitions
sigmoid_steepness = 3.0

# Exponential decay rate for time-based metrics
exponential_decay_rate = 0.5

[kaizen_thresholds]
# Minimum improvement percentage to trigger kaizen event
min_improvement_percent = 5.0

# Maximum regression percentage before alert
max_regression_percent = 10.0

# Number of samples needed for trend analysis
trend_sample_size = 10