[package]
name = "depyler-annotations"
version = "0.1.1"
edition = "2021"
description = "Annotation parsing and processing for Depyler"

[dependencies]
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]