[package]
name = "depyler-quality"
version = "0.1.1"
edition = "2021"
description = "Quality gates and metrics for Depyler"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
smallvec = { version = "1.0", features = ["serde"] }
depyler-core = { path = "../depyler-core" }
depyler-analyzer = { path = "../depyler-analyzer" }
depyler-annotations = { path = "../depyler-annotations" }
tempfile = "3.2"

[dev-dependencies]